apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: webserver
        image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
        ports:
        - containerPort: 80
